# Shared defaults; other configs inherit/override by simple YAML load+update
mode: mock              # mock | ollama
paths:
  out_dir: results/run-mock
  artifacts_dir: results/artifacts
cache:
  type: semantic        # semantic | exact
  max_size: 5
  clean_size: 2
  eviction: LRU         # LRU | FIFO
  similarity: distance  # distance | cosine | exact
  onnx_model: null      # or name/path if needed
run:
  prompts: 10
  warm_repeats: 1
  prompt_prefix: "What is caching? "
metrics:
  sample_interval_ms: 300
plot:
  group_by: [mode, cache.type, cache.max_size]
