mode: mock
cache:
  type: semantic
  eviction: COST_AWARE
  max_size: 5
  clean_size: 2
  similarity: distance
  similarity_threshold: 0.98
  cost_metric: latency_ms   # or: tokens
  cost_decay: 0.0
paths:
  artifacts_dir: results/mock-cost
  out_dir: results/mock-cost/run1
  reset_artifacts: true
run:
  prompts: 10
  warm_repeats: 1
  reverse_warm: true
  strict_cold: true
  # prompts_file: "data/prompts_mixed.txt"   
