paths:
  out_dir: results/knobs/costaware_largeN
  artifacts_dir: results/knobs/costaware_largeN/artifacts
  reset_artifacts: true

cache:
  type: semantic
  max_size: 128         # small vs big N → lots of evictions
  clean_size: 1
  similarity: distance
  similarity_threshold: 0.98
  cost_metric: latency_ms
  cost_decay: 0.0

run:
  prompts_file: "data/lmsys_user_prompts_expbiased_60k.txt"
  strict_cold: true
  shuffle_warm: true
  warm_repeats: 1

  # bench-only synthetic latency (OFF by default; ON here)
  mock_latency:
    profile: bimodal
    hi_ms: 80
    lo_ms: 2
    hi_frac: 0.20
    jitter_ms: 2
